// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
}

subprojects { module ->
    module.plugins.withId('com.android.application') { module.apply from: rootProject.file('gradle/property-logging.gradle') }
    module.plugins.withId('com.android.library') { module.apply from: rootProject.file('gradle/property-logging.gradle') }
}
