pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        maven { url 'https://jitpack.io' }
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/central' }
        mavenCentral()
        maven { url 'https://jitpack.io' }
        flatDir {
            dirs 'libs',
                    'libs/hq001',
                    'libs/hq002'
        }
    }
}

rootProject.name = "AD_APP"
include ':app'
include ':ad-sdk'
include ':ad-sdk-modern'
include ':ad-sdk-modern-no-ump'
include ':ad-sdk-gam-vast'
include ':ad-sdk-gam-vast-demo'
include ':hq008-flow-sdk'
include ':hq008-flow-demo'

include ':ad-sdk-fusion'
include ':ad-sdk-fusion-tcl-base'
project(':ad-sdk-fusion-tcl-base').projectDir = file('ad-sdk-fusion/vendor/base')
include ':ad-sdk-fusion-tcl-media'
project(':ad-sdk-fusion-tcl-media').projectDir = file('ad-sdk-fusion/vendor/media')
include ':ad-sdk-fusion-tcl-player'
project(':ad-sdk-fusion-tcl-player').projectDir = file('ad-sdk-fusion/vendor/player')
