plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.smart.android.adsdk.gamvast.demo'
    compileSdk 36

    defaultConfig {
        applicationId 'com.smart.android.adsdk.gamvast.demo'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
        manifestPlaceholders += [
            adAppId    : 'ca-app-pub-3199037222330432~1558586642',
            adChannelId: 'GOOGLE_AD_TV_CVTE'
        ]
    }

    signingConfigs {
        h713 {
            storeFile rootProject.file('app/h713.jks')
            storePassword '123456'
            keyAlias 'h713'
            keyPassword '123456'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.h713
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.h713
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.github.code-rebooter.ad-app:ad-sdk-modern:v1.0.13'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}
