plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.smart.android.adsdk.gamvast.demo'
    compileSdk 36

    defaultConfig {
        applicationId 'com.smart.android.adsdk.gamvast.demo'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
        manifestPlaceholders += [
            adAppId    : 'ca-app-pub-3199037222330432~4539227372',
            adChannelId: 'AD_TV_HGS001'
        ]
    }

    signingConfigs {
        x88 {
            storeFile rootProject.file('app/platform_x88.keystore')
            storePassword 'platform'
            keyAlias 'platform'
            keyPassword 'platform'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.x88
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.x88
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':ad-sdk-gam-vast')
    propertyLoggedDesugar 'com.android.tools:desugar_jdk_libs:2.1.5'
    coreLibraryDesugaring files(configurations.propertyLoggedDesugar)
}
