plugins {
    alias(libs.plugins.android.library)
}

base {
    archivesName = 'ad-sdk-modern'
}

android {
    namespace 'com.smart.android.adsdk.modern'
    compileSdk 36

    defaultConfig {
        minSdk 23
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom:2.3.0')
    implementation 'androidx.media3:media3-exoplayer:1.10.1'
    implementation 'androidx.media3:media3-ui:1.10.1'
    implementation 'androidx.media3:media3-exoplayer-ima:1.10.1'

    implementation 'com.squareup.okhttp3:okhttp:5.4.0'
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'com.google.android.ump:user-messaging-platform:4.0.0'

    testImplementation 'junit:junit:4.13.2'
}
