plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.smart.android.ad_app'
    compileSdk 36

    defaultConfig {
        applicationId "com.smart.android.ad_app"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
            java.srcDirs = ['src/main/java']
        }

        hq001 {
            java.srcDirs = ['src/hq001/java']
        }

        hq002 {
            java.srcDirs = ['src/hq002/java']
        }

        hq003 {
            java.srcDirs = ['src/hq003/java']
        }
        hq004 {
            java.srcDirs = ['src/hq004/java']
        }
        hq005 {
            java.srcDirs = ['src/hq005/java']
        }
        hq006 {
            java.srcDirs = ['src/hq006/java']
        }
    }

    signingConfigs {

        hikeen {
            storeFile file("HikeenKeystore.jks")
            storePassword '123456'
            keyAlias 'zeasn'
            keyPassword '123456'
        }

        h713 {
            storeFile file("h713.jks")
            storePassword "123456"
            keyAlias "h713"
            keyPassword "123456"
        }

        x88 {
            storeFile file("platform_x88.keystore")
            storePassword "platform"
            keyAlias "platform"
            keyPassword "platform"
        }

        yxt {
            storeFile file("yxt_X98K_10.keystore")
            //storeFile file("platform_X98K_301.keystore")
            storePassword "android"
            keyAlias "platform"
            keyPassword "android"
        }

    }

    buildTypes {
        release {
            minifyEnabled true
            zipAlignEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug{
            minifyEnabled false
            signingConfig signingConfigs.h713
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    flavorDimensions.add("ad")

    productFlavors {
        hq001 {
            applicationId "com.hqota.launcher.hq"
            versionCode 1   // 2025-7-29发布版本号：1
            versionName "1.0.1"     // 2025-7-29发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.hikeen
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }

        hq002 {
            applicationId "com.hqota.launcher.slfhq"
            versionCode 1   // 2025-7-29发布版本号：1
            versionName "1.0.1"     // 2025-7-29发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.h713
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }

        hq003 {
            applicationId "com.hqota.launcher.liuhq"
            versionCode 1   // 2025-7-29发布版本号：1
            versionName "1.0.1"     // 2025-7-29发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.hikeen
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }

        hq004 {
            applicationId "com.hqota.launcher.aduhq"
            versionCode 1   // 2025-7-31发布版本号：1
            versionName "1.0.1"     // 2025-7-31发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.h713
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }

        hq005 {
            //这个yxt签名文件跟com.chihim.launcher.x98m是对应的，不能随意该任何一个，不然无法展示广告
            applicationId "com.chihim.launcher.x98m"
            versionCode 1   // 2025-7-31发布版本号：1
            versionName "1.0.1"     // 2025-7-31发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.yxt
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }

        hq006 {
            applicationId "io.android.ad.dyrtb"
            versionCode 1   // 2025-12-4发布版本号：1
            versionName "1.0.1"     // 2025-12-4发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.h713
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }

    }

}


android.applicationVariants.all { variant ->
    def flavor = variant.flavorName
    def libsDir = file("libs/${flavor}")
    if (libsDir.exists()) {
        def filesToLoad = fileTree(dir: libsDir, include: ['*.jar', '*.aar'])
        def dependency = project.dependencies.create(filesToLoad)
        variant.getCompileConfiguration().dependencies.add(dependency)
        variant.getRuntimeConfiguration().dependencies.add(dependency) // ✅ 必须加这句！
    }
}


dependencies {

    implementation libs.androidx.core.ktx

    //noinspection UseTomlInstead
    implementation 'io.github.code-rebooter:lib_autorun:1.0.61-alpha.4'
    //noinspection UseTomlInstead
    compileOnly "androidx.fragment:fragment-ktx:1.8.9"   //打正式版本要去掉这个依赖，包括MainActivity

    //noinspection UseTomlInstead
    hq001Implementation ('com.google.guava:guava:33.5.0-android')
    //hq001Implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    //hq001Implementation 'com.google.code.gson:gson:2.12.1'

    //noinspection UseTomlInstead
    hq003Implementation 'com.squareup.retrofit2:adapter-rxjava2:3.0.0'
    //noinspection UseTomlInstead
    hq003Implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    //noinspection UseTomlInstead
    hq003Implementation 'androidx.media3:media3-exoplayer:1.8.0'
    //noinspection UseTomlInstead
    hq003Implementation 'androidx.media3:media3-ui:1.8.0'
    //noinspection UseTomlInstead
    hq003Implementation 'androidx.media3:media3-exoplayer-ima:1.8.0'
    //noinspection UseTomlInstead
    hq003Implementation "io.reactivex.rxjava2:rxjava:2.2.21"
    //noinspection UseTomlInstead
    hq003Implementation "io.reactivex.rxjava2:rxandroid:2.1.1"

    //hq004Implementation 'com.google.code.gson:gson:2.12.1'
    //hq004Implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    //noinspection UseTomlInstead
    hq004Implementation 'androidx.media3:media3-exoplayer:1.8.0'

    //noinspection UseTomlInstead
    hq005Implementation ('com.google.guava:guava:33.5.0-android')
    //hq005Implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    //hq005Implementation 'com.google.code.gson:gson:2.12.1'

    //noinspection UseTomlInstead
    hq006Implementation "androidx.media3:media3-ui:1.8.0"
    //noinspection UseTomlInstead
    hq006Implementation "androidx.media3:media3-exoplayer:1.8.0"
    // The library adds the IMA ExoPlayer integration for ads.
    //noinspection UseTomlInstead
    hq006Implementation "androidx.media3:media3-exoplayer-ima:1.8.0"

    //noinspection UseTomlInstead
    api 'com.github.codeZeng95:lib_dimen:1.0.1'

}