plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.smart.android.ad_app'
    compileSdk 36

    defaultConfig {
        applicationId "com.smart.android.ad_app"
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
            java.srcDirs = ['src/main/java']
        }

        hq001 {
            java.srcDirs = ['src/hq001/java']
        }

        hq002 {
            java.srcDirs = ['src/hq002/java']
        }

        hq003 {
            java.srcDirs = ['src/hq003/java']
        }
    }

    signingConfigs {

        hikeen {
            storeFile file("HikeenKeystore.jks")
            storePassword '123456'
            keyAlias 'zeasn'
            keyPassword '123456'
        }

        h713 {
            storeFile file("h713.jks")
            storePassword "123456"
            keyAlias "h713"
            keyPassword "123456"
        }

        x88 {
            storeFile file("platform_x88.keystore")
            storePassword "platform"
            keyAlias "platform"
            keyPassword "platform"
        }

    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    flavorDimensions.add("ad")

    productFlavors {
        hq001 {
            applicationId "com.hqota.launcher.hq"
            minSdk 21
            versionCode 1   // 2025-7-29发布版本号：1
            versionName "1.0.1"     // 2025-7-29发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.h713
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }

        hq002 {
            applicationId "com.hqota.launcher.hq1"
            minSdk 21
            versionCode 1   // 2025-7-29发布版本号：1
            versionName "1.0.1"     // 2025-7-29发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.h713
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }

        hq003 {
            applicationId "com.hqota.launcher.hq2"
            minSdk 21
            versionCode 1   // 2025-7-29发布版本号：1
            versionName "1.0.1"     // 2025-7-29发布版本名：1.0.1
            dimension "ad"
            signingConfig signingConfigs.h713
            manifestPlaceholders = [share_uid: "android.uid.system"]
            buildConfigField "String", "BASE_URL", '"https://api.gp0312.cc/"'
            buildConfigField "String", "APP_ID", '"ad"'
            buildConfigField "String", "CHANNEL", '"HQTV_GD"'
            buildConfigField "String", "C_TYPE", '"HQTV_GD"'
            buildConfigField "String", "MODEL", '"HQTV_GD"'
            buildConfigField "boolean", "IS_ENCRYPTED", "false" // 默认值为false
            buildConfigField "String", "MD5_VALUE", '"H4sIAAAAAAAAAMuX3FR5Jn9nofVvAAt++nAKAAAA"'
            buildConfigField "String", "BACKUP_DOMAIN", '"https://api.g5movie.cc/"'
        }
    }

}


android.applicationVariants.all { variant ->
    def flavor = variant.flavorName
    def libsDir = file("libs/${flavor}")
    if (libsDir.exists()) {
        def filesToLoad = fileTree(dir: libsDir, include: ['*.jar', '*.aar'])
        def dependency = project.dependencies.create(filesToLoad)
        variant.getCompileConfiguration().dependencies.add(dependency)
        variant.getRuntimeConfiguration().dependencies.add(dependency) // ✅ 必须加这句！
    }
}


dependencies {

    implementation libs.androidx.core.ktx
    implementation files('libs/lib_autorun.aar')
    api 'com.squareup.okhttp3:okhttp:4.12.0'
    api 'com.google.code.gson:gson:2.12.1'
    api "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
    api "androidx.work:work-runtime-ktx:2.9.0"
    implementation "androidx.fragment:fragment:1.8.8"   //打正式版本要去掉这个依赖，包括MainActivity

    hq001Implementation ('com.google.guava:guava:31.1-android')
    hq001Implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    hq001Implementation 'com.google.code.gson:gson:2.10.1'
}