plugins {
    alias(libs.plugins.android.library)
}

def hq008FlowSdkVersionCode = 8
def hq008FlowSdkVersionName = '2.0.8'
def hq008FlowSdkBuildTime = new java.text.SimpleDateFormat('yyyyMMdd_HHmm').format(new Date())

version = hq008FlowSdkVersionName
archivesBaseName = "${project.name}-v${hq008FlowSdkVersionName}-${hq008FlowSdkBuildTime}"

android {
    namespace 'com.smart.android.hq008flow'
    compileSdk 36

    defaultConfig {
        minSdk 23
        consumerProguardFiles 'consumer-rules.pro'
        buildConfigField 'int', 'SDK_VERSION_CODE', "${hq008FlowSdkVersionCode}"
        buildConfigField 'String', 'SDK_VERSION_NAME', "\"${hq008FlowSdkVersionName}\""
        buildConfigField 'String', 'SDK_BUILD_TIME', "\"${hq008FlowSdkBuildTime}\""
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
    implementation 'com.google.code.gson:gson:2.8.9'
    testImplementation 'junit:junit:4.13.2'
}
